# This workflow takes ssh connection to Guild's server, pulls latest
# changes and restarts bot in new tmux session.

name: Update bot on Guild's server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Execute commands via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          tmux kill-session -t kiltisbot
          cd fk-kiltisbot
          git pull
          tmux new-session -d -s kiltisbot \
          "source env/bin/activate &&
          pip install -r requirements.txt &&
          python3 bot.py"
